import { TimetableElement } from "@/types/timetable";

export const timetable: TimetableElement[][] = [
  [
    {
      subject: "Казахский",
      teacher: "Конурова Н.А./Оспангалиева М.Т.",
      auditory: "1к310/1к326",
      id: 2,
      variable: 0,
      type: "seminar",
    },
    {
      subject: "Основы программирования",
      teacher: "Тау А. Ғ.",
      auditory: "Гк405",
      id: 3,
      variable: 1,
      type: "lection",
    },
    {
      subject: "Основы программирования",
      teacher: "Тау А. Ғ.",
      auditory: "Гк414",
      id: 3,
      variable: 2,
      type: "seminar",
    },
  ],
  [
    {
      subject: "Английский",
      teacher: "Богданова А.А./Питиримова Т.В.",
      auditory: "1к415/1к423",
      id: 1,
      variable: 0,
      type: "seminar",
    },
    {
      subject: "Физ-ра",
      teacher: "Кужахметов С.Б.",
      auditory: "-",
      id: 2,
      variable: 0,
      type: "seminar",
    },
  ],
  [
    {
      subject: "Математика",
      teacher: "Журов В. В.",
      auditory: "1к209",
      id: 1,
      variable: 1,
      type: "lection",
    },
    {
      subject: "Физика",
      teacher: "Алдаберген І.Е./Кузнецова Ю.А.",
      auditory: "1к428/1к401",
      id: 1,
      variable: 2,
      type: "lab",
    },
    {
      subject: "Математика",
      teacher: "Журов В. В.",
      auditory: "1к314",
      id: 2,
      variable: 0,
      type: "seminar",
    },
  ],
  [
    {
      subject: "Английский",
      teacher: "Богданова А.А./Питиримова Т.В.",
      auditory: "1к415/1к423",
      id: 3,
      variable: 2,
      type: "seminar",
    },
    {
      subject: "Казахский",
      teacher: "Конурова Н.А./Оспангалиева М.Т.",
      auditory: "1к310/1к326",
      id: 3,
      variable: 1,
      type: "seminar",
    },
    {
      subject: "Основы программирования",
      teacher: "Кисина М. К.",
      auditory: "Гк400",
      id: "4/2",
      variable: 0,
      type: "lab",
    },
  ],
  [
    {
      subject: "Кураторский Час",
      teacher: "Головачёва В.Н.",
      auditory: "Гл.300д",
      id: 0,
      variable: 0,
      type: "seminar",
    },
    {
      subject: "Физика",
      teacher: "Кузнецова Ю.А.",
      auditory: "1к428",
      id: 2,
      variable: 2,
      type: "seminar",
    },
    {
      subject: "Физика",
      teacher: "Кузнецова Ю.А.",
      auditory: "1к426",
      id: 2,
      variable: 1,
      type: "lection",
    },
    {
      subject: "Физ-ра",
      teacher: "Кужахметов С.Б.",
      auditory: "-",
      id: 3,
      variable: 0,
      type: "seminar",
    },
  ],
];
