import { TimetableElement } from "@/types/timetable";

export const timetable: TimetableElement[][] = [
  [
    {
      subject: "ИКТ",
      teacher: "Кан О.А.",
      auditory: "Гл.350",
      id: 1,
      variable: 1,
      type: "lection",
    },
    {
      subject: "Математика",
      teacher: "Журов В. В.",
      auditory: "1к314",
      id: 2,
      variable: 0,
      type: "seminar",
    },
  ],
  [
    {
      subject: "Английский",
      teacher: "Богданова А.А./Питиримова Т.В.",
      auditory: "1к415/1к423",
      id: 1,
      variable: 2,
      type: "seminar",
    },
    {
      subject: "Физ-ра",
      teacher: "Кужахметов С.Б.",
      auditory: "-",
      id: 2,
      variable: 0,
      type: "seminar",
    },
    {
      subject: "История Казахстана",
      teacher: "Темиргалиев К.А.",
      auditory: "1к230",
      id: 3,
      variable: 0,
      type: "seminar",
    },
  ],
  [
    {
      subject: "Кураторский Час",
      teacher: "Головачёва В.Н.",
      auditory: "Гл.300д",
      id: 0,
      variable: 0,
      type: "seminar",
    },
    {
      subject: "Казахский",
      teacher: "Конурова Н.А./Оспангалиева М.Т.",
      auditory: "1к324/1к326",
      id: 2,
      variable: 0,
      type: "seminar",
    },
    {
      subject: "ИКТ",
      teacher: "Мухамедиева Л.С./Дуганова Г.К.",
      auditory: "1к253/1к255",
      id: 3,
      variable: 0,
      type: "lab",
    },
  ],
  [
    {
      subject: "Математика",
      teacher: "Журов В.В.",
      auditory: "Гл.350",
      id: 1,
      variable: 1,
      type: "lection",
    },
    {
      subject: "Английский",
      teacher: "Богданова А.А./Питиримова Т.В.",
      auditory: "1к415 / 1к417",
      id: 2,
      variable: 0,
      type: "seminar",
    },
  ],
  [
    {
      subject: "Казахский",
      teacher: "Конурова Н.А./Оспангалиева М.Т.",
      auditory: "1к324/1к326",
      id: 2,
      variable: 1,
      type: "seminar",
    },
    {
      subject: "Физ-ра",
      teacher: "Кужахметов С.Б.",
      auditory: "-",
      id: 3,
      variable: 0,
      type: "seminar",
    },
    {
      subject: "История Казахстана",
      teacher: "Амерханова Ж.Б.",
      auditory: "Гл.352",
      id: 4,
      variable: 2,
      type: "lection",
    },
  ],
];
